### ISSUE TITLE
Power button should not suspend in GNOME

### ISSUE THREAD

**Issue by gaudenz** [imedias/lernstickAdvanced#10]
While suspend as a default is fine for a system installed on an internal disk, this is not really the best thing to do for a live system as the live medium might be gone by the time the system wakes up.

The default should be to ask the user what to do, at least for the exam environment as we don't want to suspend there.

**Comment by ronnystandtke** [comment]
fixed in lernstick-usertemplate 31

**Comment by gaudenz** [comment]
Wäre noch cool wen du da das commit verlinken würdest. Dann sieht man auch was die Lösung war.

**Comment by ronnystandtke** [comment]
https://github.com/imedias/lernstick-usertemplate/commit/8b59f45848b31b5ce60c62af67b61cc7f037a5f0

**Comment by gaudenz** [comment]
Thanks a lot!
